# Hacky temporary database configuration just to keep Rails
# 1.2 from breaking and stop ActiveRecord complaining. This
# is required due to a Rails bug. See Rails tickets 6785
# and 7868 for details:
#
#   http://dev.rubyonrails.org/ticket/6795
#   http://dev.rubyonrails.org/ticket/7868  

dbinfo: &dbinfo
  adapter: postgresql
  host: /home/rool/postgres/
  username: rool
  password: oiarfewa
  
development:
  <<: *dbinfo
  database: hub-test

test:
  <<: *dbinfo
  database: hub-test

production:
  <<: *dbinfo
  database: hub-test
